const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger.json';
const endpointsFiles = ['./server.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "Polskie Winnice REST API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "polskiewinnice.ovh",
    servers: [
        {
            url: "http://localhost:3000/api/v1",
        },
    ],
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
};

swaggerAutogen(outputFile, endpointsFiles, doc);
