name: remote ssh command
on: [push]
jobs:
  auto-pull:
    name: PullOrigin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       repository: KamilDwo/winnice_routing
    - run: |
        git remote -v
        git pull
