name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
         cd ..
         cd var/www/vhosts/polskiewinnice.pl/api.polskiewinnice.pl
         ls
         git config --global user.name "KamilDwo"
         git config --global user.email "kontakt@heartit.pl"
         git pull
         KamilDwo
